ARG BASE

FROM ${BASE}

ARG AUTHOR
ARG VERSION

LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

COPY ./dist/kube-vip-${TARGETOS}-${TARGETARCH} /usr/local/bin/kube-vip

ENTRYPOINT ["kube-vip"]
